#!/bin/bash

echo "=================================="
echo "🚀 GRAFANA SETUP COMPLETE!"
echo "=================================="
echo ""
echo "✅ Status: RUNNING"
echo "🌐 URL: http://localhost:3001"
echo ""
echo "👤 Login Credentials:"
echo "   Username: admin"
echo "   Password: admin"
echo "   (Change password after first login)"
echo ""
echo "📊 Pre-loaded Dashboards:"
echo "   1. Live Operations Monitor"
echo "   2. Carrier Performance & Coverage"
echo "   3. Exception & Delay Tracking"
echo ""
echo "🗄️  Database Connected:"
echo "   Host: serhafen-db-postgres-staging.cluster-chgg2qqoy9y6.us-east-1.rds.amazonaws.com"
echo "   Database: nucleo"
echo "   Status: Auto-configured ✅"
echo ""
echo "=================================="
echo "NEXT STEPS:"
echo "=================================="
echo "1. Open browser: http://localhost:3001"
echo "2. Login with admin/admin"
echo "3. Go to Dashboards → Browse"
echo "4. Explore your 3 pre-built dashboards!"
echo ""
echo "📖 Full documentation: ~/grafana-setup/README.md"
echo ""
echo "=================================="
echo "USEFUL COMMANDS:"
echo "=================================="
echo "Stop Grafana:     docker-compose down"
echo "Restart Grafana:  docker-compose restart"
echo "View Logs:        docker-compose logs -f grafana"
echo "Check Status:     docker ps | grep grafana"
echo ""
